# fly.toml app configuration file generated for notetaking-app on 2023-07-24T23:03:53+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "notetaking-app"
primary_region = "waw"
kill_signal = "SIGINT"
kill_timeout = "5s"
console_command = "/code/manage.py shell"

[deploy]
  release_command = "python manage.py migrate --noinput"

[env]
  PORT = "8000"

[[services]]
  protocol = "tcp"
  internal_port = 8000
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

[[statics]]
  guest_path = "/code/static"
  url_prefix = "/static/"
